CREATE TABLE IF NOT EXISTS boosts (
    id SERIAL PRIMARY KEY,
    shoutout_id INTEGER NOT NULL REFERENCES shoutouts(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    points INTEGER DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
